### ISSUE TITLE
dir-info2.sh why do we need BUFFER?

### ISSUE THREAD

**Issue by smirnov1993** [iamsaywhat/dir-info#4]
Can't we print the results line by line?

**Comment by iamsaywhat** [comment]
The link below you can see the description of the commit, which says why it is necessary.
https://github.com/iamsaywhat/dir-info/commit/d349a7433c867e2f8b79ec339709c9665dbebb22

To illustrate this:
This is how it works without concatenating in BUFFER
![Screenshot from 2020-09-10 18-38-28](https://user-images.githubusercontent.com/59166809/92755825-e4f21080-f394-11ea-9c3b-adeb53afc6fb.png)
And this is how it works with BUFFER
![Screenshot from 2020-09-10 18-36-01](https://user-images.githubusercontent.com/59166809/92755869-ede2e200-f394-11ea-9642-9ef832d7d13f.png)
